# Generated by Django 4.2.6 on 2023-10-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntavecinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NombreDocumento', models.CharField(max_length=100, verbose_name='Nombre del Documento')),
                ('TipoDocumento', models.CharField(max_length=50, verbose_name='Tipo de Documento')),
                ('FechaPublicacion', models.DateField(verbose_name='Fecha de Publicación')),
                ('DescripcionDocumento', models.TextField(verbose_name='Descripción del Documento')),
                ('Archivo', models.FileField(upload_to='documents/', verbose_name='Archivo del Documento')),
            ],
        ),
        migrations.AlterField(
            model_name='vecinos',
            name='certificado',
            field=models.ImageField(upload_to='images/certificados/', verbose_name='Certificado de residencia'),
        ),
    ]
