# Generated by Django 4.2.6 on 2023-10-29 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juntavecinos', '0002_documentos_alter_vecinos_certificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuntaVecinos',
            fields=[
                ('Junta_Vecinos_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Administrador', models.CharField(max_length=100)),
                ('Ciudad', models.CharField(max_length=50)),
                ('Localidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TiposPerfil',
            fields=[
                ('Tipo_Perfil_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Perfil', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reuniones',
            fields=[
                ('Reuniones_id', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Lugar', models.CharField(max_length=100)),
                ('Asunto', models.CharField(max_length=100)),
                ('Descripcion_reuniones', models.TextField(max_length=500)),
                ('Proyecto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juntavecinos.proyectos')),
            ],
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('Notificaciones_id', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo_notificaciones', models.CharField(max_length=100)),
                ('Contenido', models.CharField(max_length=100)),
                ('FechaEnvio', models.DateTimeField()),
                ('Tipo_notificaciones', models.CharField(max_length=20)),
                ('Destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juntavecinos.vecinos')),
            ],
        ),
        migrations.CreateModel(
            name='Certificados',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('FechaSolicitud', models.DateField()),
                ('Aprobado', models.BooleanField()),
                ('Vecino_RUT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juntavecinos.vecinos')),
            ],
        ),
    ]
