# Generated by Django 4.2.6 on 2023-10-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntavecinos', '0005_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='archivo',
            field=models.FileField(upload_to='documentos/', verbose_name='Archivo del Documento'),
        ),
    ]
