# Generated by Django 4.2.6 on 2023-11-06 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juntavecinos', '0006_alter_documentos_archivo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documento',
        ),
    ]
