# Generated by Django 4.2.6 on 2023-11-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntavecinos', '0007_delete_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='fecha_publicacion',
            field=models.DateTimeField(editable=False, verbose_name='Fecha de Publicación'),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='tipo_documento',
            field=models.CharField(choices=[('Certificado de residencia', 'Certificado de residencia'), ('Boleta', 'Boleta')], max_length=50, verbose_name='Tipo de Documento'),
        ),
    ]
