# Generated by Django 3.2.8 on 2023-11-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntavecinos', '0009_documentos_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='TipoSolicitud',
            field=models.CharField(choices=[['Eventos', 'Eventos'], ['Programas educativos', 'Programas educativos'], ['Deportes', 'Deportes'], ['Concursos', 'Concursos'], ['Comités de vecinos', 'Comités de vecinos'], ['Otros', 'Otros']], max_length=100, verbose_name='Tipo de Actividad'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='Tipo',
            field=models.CharField(choices=[['Seguridad', 'Seguridad'], ['Programas educativos', 'Programas educativos'], ['Eventos', 'Eventos'], ['Mejoras de infraestructura', 'Mejoras de infraestructura'], ['Comités de vecinos', 'Comités de vecinos'], ['Otros', 'Otros']], max_length=100, verbose_name='Tipo de noticia'),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='TipoSolicitud',
            field=models.CharField(choices=[['Seguridad', 'Seguridad'], ['Mejora de calles', 'Mejora de calles'], ['Eventos', 'Eventos'], ['Mejoras de infraestructura', 'Mejoras de infraestructura'], ['Concursos', 'Concursos'], ['Otros', 'Otros']], max_length=100, verbose_name='Tipo de propuesta'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='TipoProyecto',
            field=models.CharField(choices=[['Seguridad', 'Seguridad'], ['Programas educativos', 'Programas educativos'], ['Eventos', 'Eventos'], ['Mejoras de infraestructura', 'Mejoras de infraestructura'], ['Comités de vecinos', 'Comités de vecinos'], ['Otros', 'Otros']], max_length=100, verbose_name='Tipo de proyecto'),
        ),
    ]
